name: utils
channels:
  - conda-forge
dependencies:
  - python=3.12
  - tmux
  - fish
  - chezmoi
  - supervisor
  - nvim
  - fzf
  - lazygit
  - postgresql
  - htop
  - yazi
  - gh
  - pip
  - pip:
      - basedpyright
      - ruff
      - nvitop
