name: utils
channels:
  - conda-forge
dependencies:
  - python=3.12
  - tmux
  - chezmoi
  - supervisor
  - yazi
  - nvitop
  - nvim
  - fzf
  - ripgrep
  - fd-find
  - lazygit
  - git-lfs
  - postgresql
  - pip
  - pip:
     - pyyaml
     - huggingface_hub
