[[manager.prepend_keymap]]
on   = [ "<C-s>" ]
run  = 'shell "fish $HOME/.config/yazi/yazi.fish \"$0\" \"$@\"" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on   = [ "l" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = [ "c", "s" ]
run  = "plugin --sync smart-enter --args='download'"
desc = "Download file"
